"""Add Telegram linking fields

Revision ID: 0004_telegram_fields
Revises: 0003_feeds_notifications
Create Date: 2026-05-02 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0004_telegram_fields"
down_revision: Union[str, None] = "0003"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("telegram_link_token", sa.String(length=255), nullable=True))
    op.add_column("users", sa.Column("telegram_link_token_expires_at", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "telegram_link_token_expires_at")
    op.drop_column("users", "telegram_link_token")
    # ### end Alembic commands ###
